language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
script: npm run build
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  # this following script could be used in the future if we want to test functionality on other branches 
  # - provider: script # Run a custom deployment script which we will define below
  #   script: now --token $NOW_TOKEN
  #   skip_cleanup: true
  #   on:
  #     all_branches: true
  #     master: false
  - provider: script
    script: now --token $NOW_TOKEN --no-verify && now alias --token $NOW_TOKEN --no-verify
    skip_cleanup: true
    on:
      master: true